// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdoh9XHR7eINLdm_26lG8aL5FWTToBVzY',
    appId: '1:72255034329:web:09e71ae96ca50ef9aebfc8',
    messagingSenderId: '72255034329',
    projectId: 'omedia-c57dd',
    authDomain: 'omedia-c57dd.firebaseapp.com',
    storageBucket: 'omedia-c57dd.firebasestorage.app',
    measurementId: 'G-9RWN03DFZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9hDQKVwCFSx-syUgdS_6UNOIKBAbc3Ac',
    appId: '1:72255034329:android:d2dab35dc4ab8eb1aebfc8',
    messagingSenderId: '72255034329',
    projectId: 'omedia-c57dd',
    storageBucket: 'omedia-c57dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WDj5q1gSD_UdGYpVA0VqVlyVC28WBMc',
    appId: '1:72255034329:ios:db8ee6d940da53cdaebfc8',
    messagingSenderId: '72255034329',
    projectId: 'omedia-c57dd',
    storageBucket: 'omedia-c57dd.firebasestorage.app',
    iosBundleId: 'com.example.omedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5WDj5q1gSD_UdGYpVA0VqVlyVC28WBMc',
    appId: '1:72255034329:ios:db8ee6d940da53cdaebfc8',
    messagingSenderId: '72255034329',
    projectId: 'omedia-c57dd',
    storageBucket: 'omedia-c57dd.firebasestorage.app',
    iosBundleId: 'com.example.omedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdoh9XHR7eINLdm_26lG8aL5FWTToBVzY',
    appId: '1:72255034329:web:eb492520668daffaaebfc8',
    messagingSenderId: '72255034329',
    projectId: 'omedia-c57dd',
    authDomain: 'omedia-c57dd.firebaseapp.com',
    storageBucket: 'omedia-c57dd.firebasestorage.app',
    measurementId: 'G-FBBDEH1HY2',
  );
}
